/**
 * Eksporterer beregnings-API for modulerne.
 */
export { aggregateResults, createDefaultResult, runModule, moduleCalculators } from './runModule'
export * from './modules/runA1'
export * from './modules/runA2'
export * from './modules/runA3'
export * from './modules/runA4'
export * from './modules/runB1'
export * from './modules/runB2'
export * from './modules/runB3'
export * from './modules/runB4'
export * from './modules/runB5'
export * from './modules/runB6'
export * from './modules/runB7'
export * from './modules/runB8'
export * from './modules/runB9'
export * from './modules/runB10'
export * from './modules/runB11'
export * from './modules/runC1'
export * from './modules/runC2'
export * from './modules/runC3'
export * from './modules/runC4'
export * from './modules/runC5'
export * from './modules/runC6'
export * from './modules/runC7'
export * from './modules/runC8'
export * from './modules/runC9'
export * from './modules/runC10'
export * from './modules/runC11'
export * from './modules/runC12'
export * from './modules/runC13'
export * from './modules/runC14'
export * from './modules/runC15'
