name: Validate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [lint, typecheck, test, build]
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: '1'
      TURBO_TELEMETRY_DISABLED: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.10.0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -w run ${{ matrix.task }}
